# Generated by Django 5.2.8 on 2025-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('post_type', models.CharField(choices=[('news', 'Новость'), ('article', 'Статья'), ('lesson', 'Урок')], max_length=10, verbose_name='Тип поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('fajr', models.TimeField(verbose_name='Фаджр')),
                ('sunrise', models.TimeField(verbose_name='Восход')),
                ('dhuhr', models.TimeField(verbose_name='Зухр')),
                ('asr', models.TimeField(verbose_name='Аср')),
                ('maghrib', models.TimeField(verbose_name='Магриб')),
                ('isha', models.TimeField(verbose_name='Иша')),
            ],
            options={
                'verbose_name': 'Время намаза',
                'verbose_name_plural': 'Времена намазов',
                'ordering': ['-date'],
            },
        ),
    ]
