# Generated by Django 5.2.8 on 2025-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTimeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prayer_times/', verbose_name='Excel файл с расписанием')),
                ('file_type', models.CharField(choices=[('current', 'Текущий файл'), ('preloaded', 'Предзагруженный файл')], default='current', max_length=10, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Файл расписания намазов',
                'verbose_name_plural': 'Файлы расписания намазов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='prayertime',
            name='city',
            field=models.CharField(default='Муслюмово', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='prayertime',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='prayertime',
            unique_together={('city', 'date')},
        ),
    ]
