# Generated by Django 5.2.8 on 2025-11-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='rutube_embed_code',
            field=models.TextField(blank=True, help_text='Скопируйте код embed с сайта Rutube', verbose_name='Код для вставки Rutube'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='rutube_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Rutube'),
        ),
    ]
